create table if not exists public.grievances (
  id bigint generated by default as identity primary key,
  ticket_id text unique not null,
  full_name text not null,
  mobile text not null,
  email text,
  district text,
  scheme_id text,
  scheme_name text,
  issue_type text not null,
  description text not null,
  consent text not null default 'yes',
  status text not null default 'In Department Review',
  created_at timestamptz not null default now()
);

alter table public.grievances enable row level security;

drop policy if exists "Anyone can submit grievances" on public.grievances;
create policy "Anyone can submit grievances"
on public.grievances for insert
to anon, authenticated
with check (true);

